packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@bufbuild/buf'
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msgpackr-extract
  - sharp

onlyBuiltDependencies:
  - mediasoup
